//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicE_commerece.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transition
    {
        public int TransitionId { get; set; }
        public int InvoiceId { get; set; }
        public System.DateTime Date { get; set; }
        public double Pay { get; set; }
        public double Due { get; set; }
        public System.DateTime Time { get; set; }
        public int Price { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
